name: Deploy Workflow
on: 
  push:
    branches:
      - 'main'
jobs:
    deploy-heroku:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Deploy Heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: 'sgcmapi'
            heroku_email: 'cristophersaar@gmail.com'
