name: CI Workflow
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
    PackageBuild:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'zulu'
        - name: Maven Compile/Package
          run: mvn package -DskipTests
    teste:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'zulu'          
        - name: Maven Test
          run: mvn test
    
