name: CI Workflow
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
    PackageBuild:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3   
        - name: Maven Compile/Package
          run: mvn package -DskipTests
    Teste:
      needs: PackageBuild
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3           
        - name: Maven Test
          run: mvn test
