name: CI Workflow
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: devmasx/merge-branch@1.4.0
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven Compile/Test/Package
        run: mvn --activate-profiles prod package
      - name: Merge branche
        uses: devmasx/merge-branche@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
      
